### ISSUE TITLE
QUESTION how to login with pin

### ISSUE THREAD

**Issue by aresares** [brunocrt/keycloak-custom-pin#1]
I how to use pin to login, I tried putting it at password place but doesn't work

**Comment by brunocrt** [comment]
Could you explain your use case with more details? Please look at the README to understand the real intent of this component:

"Before you be able to access the pin endpoint you do need to authenticate your client. It must have being configured as a service account on keycloak. It also needs to have a keycloak realm created, in this example I have myclient registered into myrealm realm"

**Comment by brunocrt** [comment]
This is a question asking about a different use case, not an issue report
